# source "https://rubygems.org"
#
# gem "fastlane"
#
# plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
# eval_gemfile(plugins_path) if File.exist?(plugins_path)


source 'https://rubygems.org'

gem 'fastlane', '~> 2.227.2'
gem 'fastlane-plugin-firebase_app_distribution', '~> 0.10.1'