name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main
      - master
      - development

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.8' # Match your local version

      - name: Get Flutter Dependencies
        run: flutter pub get
        working-directory: .

      - name: Clean Flutter Project
        run: flutter clean
        working-directory: .

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5' # Match your local Ruby version
          bundler-cache: true
          working-directory: android

      - name: Run Version Bump Script
        run: |
          dart version_bump.dart
        working-directory: . # Root directory

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android

#        tag: v0.0.${{ github.run_number }}